class Params:
    MAX_DRONE_BATTERY_VOLTAGE = 'max_drone_battery_voltage'
    MIN_DRONE_BATTERY_VOLTAGE = 'min_drone_battery_voltage'
    DRONE_BATTERY_MAX_TEMP = 'drone_battery_max_temp'
    STATION_BATTERY_MAX_TEMP = 'station_battery_max_temp'
    TRACKER_BATTERY_MAX_TEMP = 'tracker_battery_max_temp'
    ENV_MAX_TEMP = 'env_max_temp'
    ENV_MAX_HUMIDITY = 'env_max_humidity'
    ENV_MAX_RAIN_MM = 'env_max_rain_mm'
    ENV_MAX_WIND_SPEED = 'env_max_wind_speed'
    ENV_MAX_GUST = 'env_max_gust'
    MIN_SOLAR_PANELS_VOLTAGE = 'min_solar_panels_voltage'
    MIRANDA_LATT = 'miranda_latt'
    MIRANDA_LONG = 'miranda_long'
    LANDING_RADIUS = 'landing_radius'
    FAR_LANDING_RADIUS = 'far_landing_radius'
    FOLLOW_INTERVAL = 'follow_interval'
